npm install --save-dev @babel/plugin-proposal-private-methods
npm install --save assert
npm install --save ethers
npm install --save idna-uts46
npm install --save base58-js
npm install --save sha256-uint8array
npm install --save bip39
npm install --save bech32
npm install --save mweb3
npm install --save metrixjs-wallet
npm install --save bitcoinjs-message
npm install --save bitcoinjs-lib@4.0.5
npm install --save @metrixnames/mnslib
npm install --save @metrixcoin/metrilib
npm install --save bs58
npm install --save base-64
npm install --save-dev @types/base-64
npm install --save scryptsy
npm install --save-dev @types/scryptsy
npm install --save keccak
npm install --save-dev @types/keccak
npm install --save lodash
npm install --save-dev @types/lodash
npm install --save react-native-os
npm install --save react-native-tcp
npm install --save react-native-udp
npm install --save github:baydroid/mrx-address-validation
npm install --save github:baydroid/usetimeout-react-hook
npm install --save github:baydroid/react-native-user-inactivity
npm install --save react-native-exception-handler
npm install --save react-native-safe-area-context
npm install --save react-native-gesture-handler
npm install --save react-native-permissions
npm install --save react-native-reanimated
npm install --save deprecated-react-native-prop-types
npm install --save react-native-screens
npm install --save react-native-webview
npm install --save react-native-paper
npm install --save @react-native-cookies/cookies
npm install --save @react-navigation/native
npm install --save @react-navigation/bottom-tabs
npm install --save @react-navigation/stack
npm install --save @react-navigation/drawer
npm install --save github:baydroid/react-native-camera
npm install --save react-native-qrcode-scanner
npm install --save react-native-vector-icons
npm install --save @react-native-async-storage/async-storage
npm install --save react-native-crypto
npm install --save react-native-randombytes
npm install --save react-native-responsive-dimensions
npm install --save @react-native-clipboard/clipboard
npm install --save react-native-dropdown-picker
npm install --save react-native-pager-view
npm install --save react-native-tab-view
npm install --save react-native-svg
npm install --save github:baydroid/react-native-qrcode-svg
